definitions:
  controllers.bookInput:
    properties:
      author:
        type: string
      description:
        type: string
      name:
        type: string
      publisher:
        type: string
      stock:
        type: integer
    type: object
  controllers.bookResponse:
    properties:
      id:
        type: integer
      message:
        type: string
      name:
        type: string
    type: object
  controllers.borrowInput:
    properties:
      bookID:
        type: integer
      days:
        type: integer
    type: object
  controllers.borrowResponse:
    properties:
      book:
        $ref: '#/definitions/models.Book'
      borrowStatus:
        type: string
      message:
        type: string
      returnDate:
        type: string
    type: object
  controllers.getOneResponse:
    properties:
      books:
        $ref: '#/definitions/models.Book'
      message:
        type: string
    type: object
  controllers.getResponse:
    properties:
      books:
        items:
          $ref: '#/definitions/models.Book'
        type: array
      message:
        type: string
    type: object
  controllers.loginInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  controllers.loginResponse:
    properties:
      message:
        type: string
      token:
        type: string
      user:
        type: string
    type: object
  controllers.registerInput:
    properties:
      name:
        type: string
      password:
        type: string
      user_type_id:
        type: integer
    required:
    - name
    - password
    - user_type_id
    type: object
  controllers.registerResponse:
    properties:
      message:
        type: string
      user:
        type: string
    type: object
  controllers.returnInput:
    properties:
      bookID:
        type: integer
      userID:
        type: integer
    type: object
  models.Book:
    properties:
      author:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      publisher:
        type: string
      stock:
        type: integer
      updated_at:
        type: string
    type: object
  models.Borrow:
    properties:
      bookID:
        type: integer
      borrowDate:
        type: string
      created_at:
        type: string
      id:
        type: integer
      returnDate:
        type: string
      status:
        type: string
      updated_at:
        type: string
      userID:
        type: integer
    type: object
info:
  contact:
    email: sandisuryadi.mail@gmail.com
    name: Sandi Suryadi
paths:
  /book:
    get:
      description: Get all book in list.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.getResponse'
      summary: Get all book.
      tags:
      - Book
    post:
      description: Add new book to book list.
      parameters:
      - description: the body to add a book
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.bookInput'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.bookResponse'
      security:
      - BearerToken: []
      summary: Add new book.
      tags:
      - Book
  /book/{id}:
    delete:
      description: Delete a book in list.
      parameters:
      - description: Book id
        in: path
        name: id
        required: true
        type: string
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.bookResponse'
      security:
      - BearerToken: []
      summary: Delete book.
      tags:
      - Book
    get:
      description: Get a book in list.
      parameters:
      - description: Book id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.getOneResponse'
      summary: Get book by id.
      tags:
      - Book
    put:
      description: Edit a book in list.
      parameters:
      - description: Book id
        in: path
        name: id
        required: true
        type: string
      - description: the body to edit a book
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.bookInput'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.bookResponse'
      security:
      - BearerToken: []
      summary: Edit book.
      tags:
      - Book
  /borrow:
    get:
      description: Get borrow list.
      parameters:
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Borrow'
            type: array
      security:
      - BearerToken: []
      summary: Get borrow list.
      tags:
      - Borrow
    post:
      description: Add new borrow to borrow list.
      parameters:
      - description: the body to add a borrow
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.borrowInput'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.borrowResponse'
      security:
      - BearerToken: []
      summary: Add new borrow.
      tags:
      - Borrow
  /borrow/user/{user_id}:
    get:
      description: Get borrow list by user id.
      parameters:
      - description: user id
        in: path
        name: user_id
        required: true
        type: string
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Borrow'
            type: array
      security:
      - BearerToken: []
      summary: Get borrow list by user id.
      tags:
      - Borrow
  /login:
    post:
      description: Logging in to get jwt token to access api by roles.
      parameters:
      - description: the body to login a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.loginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.loginResponse'
      summary: Login as user.
      tags:
      - Login/Register
  /register:
    post:
      description: registering a user from public access.
      parameters:
      - description: the body to register a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.registerInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.registerResponse'
      summary: Register a user.
      tags:
      - Login/Register
  /return:
    put:
      description: Return book.
      parameters:
      - description: the body to return a book
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/controllers.returnInput'
      - description: 'Authorization. How to input in swagger : ''Bearer <insert_your_token_here>'''
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.borrowResponse'
      security:
      - BearerToken: []
      summary: Return book.
      tags:
      - Borrow
swagger: "2.0"
